/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sample.spring.security.resource.owner.user.password;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
